### ISSUE TITLE
publish a new version

### ISSUE THREAD

**Issue by illiptic** [alicelieutier/smoothScroll#39]
Hi,

could you please tag a new version with the latest fixes and publish it?

It's not urgent or anything, just more convenient for our project dependencies to go through npm rather than a github commit link. (we need the fix for #26 especially)

Thanks!

**Comment by alicelieutier** [comment]
npm published 0.3.0

sorry for the wait :)

**Comment by illiptic** [comment]
Wow fast, many thanks!
