### ISSUE TITLE
Chinese character in the ID can't working

### ISSUE THREAD

**Issue by scillidan** [alicelieutier/smoothScroll#52]
ni hao.
I used [Aplayer](https://github.com/MoePlayer/APlayer), which relies on Smoothscroll to make the `id` 
with Chinese characters and others (like `:||`) weren't working. 
Here's another possible [description of the problem](https://gomakethings.com/handling-chinese-and-cyrillic-character-hash-and-href-values-in-javascript/) and the [location of code](https://github.com/alicelieutier/smoothScroll/blob/master/smoothscroll.js#L99).

**Comment by cxhttt233** [comment]
+1....

**Comment by scillidan** [comment]
It's done because no use `aplayer` anymore🤡.
